### PR TITLE
Project templates

### PR DESCRIPTION
**Pull request by 0xc0170**
coide, IAR and uvision project parser to get settings for projects. I am currently testing a generic template set in the projects.yaml, need to add also support for specialized template - per project.

This is quite refactor of misc options for those tools. This leads to completely discourage users from using misc for IDE, and start using templates - create a new project, set what you need for a project and provide this project as template. Faster, easier, what else ? :-)

It's still in progress, I'll need to test this further and change mbed example repo to this new template approach, which you can see how it looks. Will share once pushed to my fork.

### CODE REVIEW

**Comment by sg-** [comment]
create a new project, set what you need for a project and provide this project as template. Faster, easier, what else ? :-)

I'd like to see what the steps are to fill out all jinja fields in the template. While there should be a few of these, it does seem like we're making a trade off between less yaml and more tmpl which is the more difficult format to edit. Would like to see a proposal on how to maintain consistency of tmpl's

**Comment by 0xc0170** [comment]
@sg- We might suppress slowly templates for most of the tools, they are hard to create/maintain. For a regular use, to create a template is tough exercise which requires to understand the tool format which is not described anywhere. I said slowly as this is a big task.

I'll test to use a template for a project and generate own files. I'll share my findings and might create a new tasks if its feasible.

**Comment by 0xc0170** [comment]
Getting closer, pgen is capable of exporting for IAR without jinja2 template file :-)

**Comment by sg-** [comment]
I think that makes me :(

**Comment by 0xc0170** [comment]
After fighting with xml formats in various projects, I made it working :smiley: Coide opens and project seems ok but does not build, some configuration ,will fix.

I sitll have to fix how to provide template. As currently I am getting uvproj or ewp files only. Need to add ewd for example or uvopt.

IAR, uvision are working .With a template provided or without template. To test this, use mbed examples, branch v0.6.
There are default values for tools, which are used if no template is provided. It is injected with pgen data and then generated back to tools format.

**Comment by 0xc0170** [comment]
Rebased on top of dev_v0.6. 

@sarahmarshy - fix_paths in coide and iar exporters are broken, can you please fix that ? They are now dics. For iar, this code breaks (path is not a path, but a dic)

```
        for path in data['source_files_lib']:
            fixed_paths.append(join('$PROJ_DIR$', rel_path, normpath(path)))
```

**Comment by 0xc0170** [comment]
CoIDE project looks good but does not build - build does not even trigger, which is strange, can't find a reason why..

**Comment by 0xc0170** [comment]
I corrected coide for now using jinja2 as it was, but compatible with project parsing. As Coide is simple , that jinja2 template was easy to edit :-) 

@sarahmarshy I fixed some issues with paths, please test !
@sg-  Can you test this feature? It's not feature complete. As a project needs a template (tools project) , it not ideal. I can prototype a parser of projects where yaml would get generated with project settings (something what we had misc). So uvision_settings.yaml would contain yaml file with all non pgen related things (all those checkboxes). I'll create an issue for that to discuss this further.

**Comment by 0xc0170** [comment]
I believe this is ready for merging to dev_v0.6 for further testing before we do official release. So many breaking changes :)

**Pull request merged**
