### PR TITLE
Changes relpath calulation for generated project files. Closes #230

### LINKED ISSUE #230: Relative paths broken?
If I define my export_dir outside of current project directory, IDE cannot find the files needed.

### PR DESCRIPTION
**Pull request by sarahmarshy**

### CODE REVIEW

**Comment by 0xc0170** [comment]
Any tests? Or how should I test, I can write one :)

**Comment by 0xc0170** [comment]
What is the path which broke  ? is it that absolute path?

**Comment by sarahmarshy** [comment]
No just "..\generated_projects"

**Comment by 0xc0170** [comment]
Ok, I'll try to write a test for that

**Pull request merged**
