### PR TITLE
IAR - debugger interface fix

### PR DESCRIPTION
**Pull request by 0xc0170**
This should fix target interface setting. We ignored this previously, and use
only name of the debugger.

@RyoheiHagimoto This should fix your problems. If you set target to swd, this should set it properly. I tested this with 7.50 version of IAR. Please send PR to progen definitions to set swd interface for your target first. And can you please test this as well?

```
    'gr-peach': {
        'mcu':'mcu/renesas/r7s721001',
        'debugger': {
            'name': 'cmsis-dap',
            'interface': 'swd',
        }
    }
```

### CODE REVIEW

**Comment by 0xc0170** [comment]
Fixes only partially #364

**Comment by RyoheiHagimoto** [comment]
@0xc0170 Thank you for your support. I can get SWD is selected in IAR IDE.

**Comment by 0xc0170** [comment]
Thanks for testing, I'll merge this and release a new patch version for both packages. We will update progen for the next mbed sdk release, so exporter should work.

.ewd parsing will come soon, to get more debugging options enabled.

**Comment by 0xc0170** [comment]
@RyoheiHagimoto published both, if you update your progen modules, you should get it running ! :-)

**Comment by RyoheiHagimoto** [comment]
@0xc0170 I tried IAR exporting with the recent revision below, and I could get SWD is selected in IAR IDE:
- [project_generator-0.8.13](https://github.com/project-generator/project_generator/commit/e30249d74fba69c62cb5b04ce08a720249d0adcd)
- [project_generator_definitions-0.2.11](https://github.com/project-generator/project_generator_definitions/commit/14fa3c40346cfba7449146e7845a01a1e70f8598)
- [mbed-SDK](https://github.com/mbedmicro/mbed/commit/1f340445d5333b485923beb9a7216fc54a8efeb4)

**Comment by 0xc0170** [comment]
Thanks for sharing

**Pull request merged**
