### PR TITLE
V0.6 Updates for uvision

### PR DESCRIPTION
**Pull request by sg-**
Couldn't get relative paths to work so had to revert those too. Also, installing from pip didnt install the dependency xml2dict but I haven't looked further at that. Just a reminder here.

### CODE REVIEW

**Comment by 0xc0170** [comment]
Thanks @sg- for those fixes, I'll look at those relative paths. Can you add thsoe fixes here only? 

why did you remove uvopt dic ? Did it cause any problems?

**Comment by 0xc0170** [comment]
I created #171 which addresses fixes here.

**Comment by 0xc0170** [comment]
I'll propose to go for 171 with uvopt fixes (I fixed uvopt and then removed it as it's automatically generated, thanks @sg-) and template condition fix. And send removing unused imports in a separate pull request.

Shall we close this one?

**Comment by sg-** [comment]
creating new PR and closing

**Pull request closed without merging**
