### PR TITLE
Sort projects by name in all commands

### LINKED ISSUE #361: Order of projects loaded - yaml.load()
Not sure what order this builds in but it doesn't seem to match the projects.yaml file or be alphabetically.

I think it should build according to projects.yaml entry order.

For example: https://github.com/mbedmicro/DAPLink/blob/master/projects.yaml yeilds:
```
(venv) C:\Developmnent\daplink> progen generate -t uvision -b
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmkl02z_if\k20dx_frdmkl02z_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_sscity_if\lpc11u35_sscity_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\sam3u2c_bl\sam3u2c_bl.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmk20dx_if\k20dx_frdmk20dx_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_arm_watch_nrf51_if\lpc11u35_arm_watch_nrf51_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmkw24f_if\k20dx_frdmkw24f_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_rblnano_if\k20dx_rblnano_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_arm_watch_stm32f411_if\lpc11u35_arm_watch_stm32f411_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\sam3u2c_nrf51dk_if\sam3u2c_nrf51dk_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmkl46z_if\k20dx_frdmkl46z_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_lpc824xpresso_if\lpc11u35_lpc824xpresso_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\sam3u2c_nrf51dongle_if\sam3u2c_nrf51dongle_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\kl26z_microbit_if\kl26z_microbit_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_bl\k20dx_bl.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_hrm1017_if\lpc11u35_hrm1017_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_archmax_if\lpc11u35_archmax_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmkl05z_if\k20dx_frdmkl05z_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_ssci824_if\lpc11u35_ssci824_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\kl26z_bl\kl26z_bl.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmk22f_if\k20dx_frdmk22f_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_c027_if\lpc11u35_c027_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_arm_watch_efm32_if\lpc11u35_arm_watch_efm32_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_archpro_if\lpc11u35_archpro_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\sam3u2c_nrf51mkit_if\sam3u2c_nrf51mkit_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_ssci1114_if\lpc11u35_ssci1114_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_rbl_if\k20dx_rbl_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_tiny_if\lpc11u35_tiny_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_archlink_if\lpc11u35_archlink_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_lpc812xpresso_if\lpc11u35_lpc812xpresso_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmkl25z_if\k20dx_frdmkl25z_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmkl26z_if\k20dx_frdmkl26z_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_efm32gg_stk_if\lpc11u35_efm32gg_stk_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\lpc11u35_archble_if\lpc11u35_archble_if.uvproj
progen.tools.uvision INFO       Project: success (0 warnings, 0 errors) build succeeded with the status: projectfiles\uvision\k20dx_frdmk64f_if\k20dx_frdmk64f_if.uvproj
```

### PR DESCRIPTION
**Pull request by theotherjimmy**
resolves #361

### CODE REVIEW

**Comment by 0xc0170** [comment]
python 3 fails

It would be nice to have previous print of projects, and after this patch to see the result

**Comment by theotherjimmy** [comment]
Working on Python 3 correction now.

I will do a before and after with DAPLink in a moment.

**Comment by theotherjimmy** [comment]
Before:
```
mbedmicro/DAPLink [ progen list projects -f projects.yaml                                   ]  0 (17:25)
k20dx_frdmkl02z_if
lpc11u35_sscity_if
sam3u2c_bl
k20dx_frdmk20dx_if
lpc11u35_arm_watch_nrf51_if
k20dx_frdmkw24f_if
k20dx_rblnano_if
lpc11u35_arm_watch_stm32f411_if
sam3u2c_nrf51dk_if
k20dx_frdmkl46z_if
lpc11u35_lpc824xpresso_if
sam3u2c_nrf51dongle_if
kl26z_microbit_if
k20dx_bl
lpc11u35_hrm1017_if
lpc11u35_archmax_if
k20dx_frdmkl05z_if
lpc11u35_ssci824_if
kl26z_bl
k20dx_frdmk22f_if
lpc11u35_c027_if
lpc11u35_arm_watch_efm32_if
lpc11u35_archpro_if
sam3u2c_nrf51mkit_if
lpc11u35_ssci1114_if
k20dx_rbl_if
lpc11u35_tiny_if
lpc11u35_archlink_if
lpc11u35_lpc812xpresso_if
k20dx_frdmkl25z_if
k20dx_frdmkl26z_if
lpc11u35_efm32gg_stk_if
lpc11u35_archble_if
k20dx_frdmk64f_if
```

After:
```
mbedmicro/DAPLink [ progen list projects -f projects.yaml                                   ]  0 (17:24)
k20dx_bl
k20dx_frdmk20dx_if
k20dx_frdmk22f_if
k20dx_frdmk64f_if
k20dx_frdmkl02z_if
k20dx_frdmkl05z_if
k20dx_frdmkl25z_if
k20dx_frdmkl26z_if
k20dx_frdmkl46z_if
k20dx_frdmkw24f_if
k20dx_rbl_if
k20dx_rblnano_if
kl26z_bl
kl26z_microbit_if
lpc11u35_archble_if
lpc11u35_archlink_if
lpc11u35_archmax_if
lpc11u35_archpro_if
lpc11u35_arm_watch_efm32_if
lpc11u35_arm_watch_nrf51_if
lpc11u35_arm_watch_stm32f411_if
lpc11u35_c027_if
lpc11u35_efm32gg_stk_if
lpc11u35_hrm1017_if
lpc11u35_lpc812xpresso_if
lpc11u35_lpc824xpresso_if
lpc11u35_ssci1114_if
lpc11u35_ssci824_if
lpc11u35_sscity_if
lpc11u35_tiny_if
sam3u2c_bl
sam3u2c_nrf51dk_if
sam3u2c_nrf51dongle_if
sam3u2c_nrf51mkit_if
```

**Comment by theotherjimmy** [comment]
@0xc0170 That's just what you ordered :smile:

**Comment by theotherjimmy** [comment]
@sg- You were the original reporter of the bug, what do you think of this new behavior?

**Comment by 0xc0170** [comment]
LGTM

**Pull request merged**
